version: '3.8'

services:
  mysql-hospital:
    image: mysql:8.0
    container_name: mysql-hospital
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Upana1234
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: Keyclo@k2026
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hospital-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-hospital
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: Keyclo@k2026
      KC_DB_PORT: 3306
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: forwarded
      KC_CACHE: local      
      KC_LOG_LEVEL: INFO
    command: 
      - "start-dev"  
    ports:
      - "8080:8080"   
    depends_on:
      mysql-hospital:
        condition: service_healthy
    networks:
      - hospital-network
    volumes:
      - keycloak_data:/opt/keycloak/data

  hospital-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-hospital-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseStringDeduplication"
      #SPRING_PROFILES_ACTIVE: docker
      #DB_URL: jdbc:mysql://mysql-hospital:3306/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guatemala
      #DB_USERNAME: keycloak_user
      #DB_PASSWORD: Keyclo@k2026
      
      # Keycloak config
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: master
      KEYCLOAK_CLIENT_ID: spring-app-client
      KEYCLOAK_CLIENT_SECRET: tu-client-secret-aqui
      
      # JPA config
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      
      # Logging
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
      LOGGING_LEVEL_COM_ZAXKER_HIKARI: DEBUG
    depends_on:
      mysql-hospital:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - hospital-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  mysql_data:
  keycloak_data:

networks:
  hospital-network:
    driver: bridge