spring:
  application:
    name: api-hospital-db
  
  datasource:
    url: jdbc:mysql://localhost:3307/?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Guatemala&characterEncoding=UTF-8
    username: ENC(AU4+A2keKEeyr0SSTG5/CdCqY+se79B9fMkfZboLwNFyzbPhKKaWk/NGNqaKz+VaSpLgkrYvIeQmsVvFA3aqJw==)
    password: ENC(Ncub+l5wZyDhAdc99QM/YEXpKxcOlJ33s3ityN72Yr0Mzhg10IGDCvE/rRdP1mvSe/t1JV9iuNWuCpO13983PQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 300000
      connection-test-query: SELECT 1
      pool-name: HikariPool-MyApp
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: non_null
    # Limitar profundidad de serialización
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        generate_statistics: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        hbm2ddl.auto: none
    hibernate:
      ddl-auto: none
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}  # Se lee de variable de entorno
    algorithm: PBEWithHMACSHA512ANDAES_256  # Algoritmo seguro
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://keycloak:8080/realms/hotel-db
#          jwk-set-uri: http://keycloak:8080/realms/hotel-db/protocol/openid-connect/certs

#  keycloak:
#    auth-server-url: http://keycloak:8080
#    realm: hotel-db
#    resource: dpi-hotel-api  # Cliente diferente para la API
#    credentials:
#      secret: TU_SECRETO_API
logging:
  level:
    com.zaxxer.hikari: DEBUG  
    org.hibernate.SQL: DEBUG  
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
    org.springframework.jdbc: DEBUG

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always